services:
  mysql-ws4:
    image: mysql:8
    container_name: mysql-ws4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webshop
    ports:
      - "3306:3306"
    volumes:
      - mysql-ws4-data:/var/lib/mysql

volumes:
  mysql-ws4-data: